version: '3.8'

services:
  monitoring-bot:
    build:
      context: .
      dockerfile: monitoring_bot/Dockerfile
    container_name: monitoring-bot
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=my-token
      - INFLUXDB_ORG=my-org
      - INFLUXDB_BUCKET=crypto_trader
    depends_on:
      - influxdb
    restart: always

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=crypto_trader
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-token
    volumes:
      - influxdb-data:/var/lib/influxdb2

volumes:
  influxdb-data:
